### ISSUE TITLE
Persistent logging of a variable's value

### ISSUE THREAD

**Issue by FergK** [FutureCensus/logify.js#4]
I often find myself need to track a variables value as it changes. My current method is to spam the console with the value, but that method has a lot of drawbacks. It would be nice to have a persistent log that displays the current value of a variable. Maybe it could be updated with the current from from an event or method that could be placed into a timer loop.

**Comment by AABoyles** [comment]
This is a great idea! Annoyingly, there aren't separate object models for logs and for logify itself. We're going to need a log object API if we want to implement this. I'll get started on it!

**Comment by AABoyles** [comment]
OK! In commit b66a777, I added a content function on the Logify global that takes zero or one arguments. Given zero, it will return the content of the last log. Given one, it will replace the content of the last log with the passed content.
